### PR TITLE
Add Coverage to tests

### LINKED ISSUE #14: Code coverage
It would be nice if you could add a code coverage badge to see what else needs testing, and whether there is any dead code.

### PR DESCRIPTION
**Pull request by PhilipVinc**
closes #14

### CODE REVIEW

**Comment by PhilipVinc** [comment]
I still need to find a way to compile the Cython module with tracing enabled only when doing CI...

**Comment by dionhaefner** [comment]
Maybe an envvar would do that you check for in `setup.py`?

**Comment by PhilipVinc** [comment]
looks like Cython is not profiling function calls, but only Cython init code..

**Comment by dionhaefner** [comment]
I'll give it a try and see if I can convince Cython to trace everything, otherwise this is good enough.

**Comment by dionhaefner** [comment]
It should work in general, but it doesn't - my guess is that this is because the code in question is called directly from XLA, not from Python. So codecov can't measure it.

I'd say we just don't run coverage on the Cython file, there's not that many branches to cover anyway (so far just the error checking and printing).

**Comment by PhilipVinc** [comment]
Ah yes! Right.
Though if we go through with your PR, then this might start hitting the methods.

--

Hmm. No. Probably not.

**Comment by dionhaefner** [comment]
No, unfortunately not (just tried it).

**Pull request merged**
