### PR TITLE
Replace setuptools_scm with vendored versioneer

### LINKED ISSUE #63: version issues
I think there are still issues with declaring our version.
I just noticed the following:

If you install mpi4jax from conda, pip cannot determine the version of mpi4jax.
This creates problems because if you have a package depending on mpi4jax installed through pip, he will attempt to reinstall mpi4jax (Eventually wreaking havoc because of mpi)

### PR DESCRIPTION
**Pull request by dionhaefner**
Fixes #63

We also need to strip all references to setuptools-scm from the conda recipe.

### CODE REVIEW

**Comment by dionhaefner** [comment]
Done. Let's pray this fixes it once and for all.

**Comment by PhilipVinc** [comment]
wait.

I think I found out how to fix conda...

**Comment by dionhaefner** [comment]
The problem with `setuptools_scm` is that we only install it as a build dependency, but if you invoke `setup.py` later you will also need it as a runtime dependency. So we could probably fix the conda recipe by making sure it's installed throughout the whole conda-forge recipe process. But I would vote to merge this regardless, since vendoring `versioneer.py` is just so much more robust.

**Comment by PhilipVinc** [comment]
no... still not working

**Review by PhilipVinc — APPROVED** [review]

**Pull request merged**
