### PR TITLE
Require cython to build extensions

### PR DESCRIPTION
**Pull request by dionhaefner**
This fixes the sdist issues

### CODE REVIEW

**Comment by PhilipVinc** [comment]
yeah I was gonna point this out

**Comment by PhilipVinc** [comment]
I think it's not solved yt
```python
➜ git checkout master
➜ python setup.py sdist
➜ pip install dist/*.tar.gz
Processing ./dist/mpi4jax-0.2.14+1.g0fbf9c1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in /Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages (from mpi4jax==0.2.14+1.g0fbf9c1) (1.20.1)
Requirement already satisfied: mpi4py>=3.0.1 in /Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages (from mpi4jax==0.2.14+1.g0fbf9c1) (3.0.3)
Requirement already satisfied: jax in /Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages (from mpi4jax==0.2.14+1.g0fbf9c1) (0.2.10)
Requirement already satisfied: absl-py in /Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages (from jax->mpi4jax==0.2.14+1.g0fbf9c1) (0.11.0)
Requirement already satisfied: opt_einsum in /Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages (from jax->mpi4jax==0.2.14+1.g0fbf9c1) (3.3.0)
Requirement already satisfied: six in /Users/filippovicentini/Documents/pythonenvs/netket_env/lib/python3.8/site-packages (from absl-py->jax->mpi4jax==0.2.14+1.g0fbf9c1) (1.15.0)
Building wheels for collected packages: mpi4jax
  Building wheel for mpi4jax (PEP 517) ... done
  Created wheel for mpi4jax: filename=mpi4jax-0.2.14+1.g0fbf9c1-cp38-cp38-macosx_10_14_x86_64.whl size=86402 sha256=80355ae11d40b18099a9c6e4a3518b72bd0a1d566af6afce5671d6af9317b9df
  Stored in directory: /Users/filippovicentini/Library/Caches/pip/wheels/0a/40/ad/db306f9763101bf68e44a2c605b9f2ccb1986176a7a383373c
Successfully built mpi4jax
Installing collected packages: mpi4jax
  Attempting uninstall: mpi4jax
    Found existing installation: mpi4jax 0.2.13
    Uninstalling mpi4jax-0.2.13:
      Successfully uninstalled mpi4jax-0.2.13
Successfully installed mpi4jax-0.2.14+1.g0fbf9c1

mpi4jax on  master [$] via netket_env via 🐍 3.8.7 took 11s
➜ ppython
zsh: command not found: ppython

mpi4jax on  master [$] via netket_env via 🐍 3.8.7
➜ python
Python 3.8.2 (default, Dec 21 2020, 15:06:04)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpi4jax
mpTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/filippovicentini/Dropbox/Ricerca/Codes/Python/mpi4jax/mpi4jax/__init__.py", line 9, in <module>
    from ._src import (  # noqa: E402
  File "/Users/filippovicentini/Dropbox/Ricerca/Codes/Python/mpi4jax/mpi4jax/_src/__init__.py", line 6, in <module>
    from . import xla_bridge  # noqa: F401
  File "/Users/filippovicentini/Dropbox/Ricerca/Codes/Python/mpi4jax/mpi4jax/_src/xla_bridge/__init__.py", line 3, in <module>
    from . import mpi_xla_bridge_cpu
ImportError: cannot import name 'mpi_xla_bridge_cpu' from partially initialized module 'mpi4jax._src.xla_bridge' (most likely due to a circular import) (/Users/filippovicentini/Dropbox/Ricerca/Codes/Python/mpi4jax/mpi4jax/_src/xla_bridge/__init__.
```

**Comment by PhilipVinc** [comment]
no never mind. 
it works

**Comment by PhilipVinc** [comment]
Previously in the `sdist` we included the tests and the example, which is handy to test the conda distribution.

Why is this no longer the case?

**Comment by dionhaefner** [comment]
I'll check. Maybe we don't need that manifest file.

**Comment by dionhaefner** [comment]
You ready for some WTF?

```bash
$ python setup.py sdist
**************************************************
*** WARNING: CUDA path not found
*** WARNING: (GPU extensions will not be built)
**************************************************
Compiling mpi4jax/_src/xla_bridge/mpi_xla_bridge.pyx because it changed.
Compiling mpi4jax/_src/xla_bridge/mpi_xla_bridge_cpu.pyx because it changed.
[1/2] Cythonizing mpi4jax/_src/xla_bridge/mpi_xla_bridge.pyx
[2/2] Cythonizing mpi4jax/_src/xla_bridge/mpi_xla_bridge_cpu.pyx
running sdist
running egg_info
creating mpi4jax.egg-info
writing mpi4jax.egg-info/PKG-INFO
writing dependency_links to mpi4jax.egg-info/dependency_links.txt
writing requirements to mpi4jax.egg-info/requires.txt
writing top-level names to mpi4jax.egg-info/top_level.txt
writing manifest file 'mpi4jax.egg-info/SOURCES.txt'
reading manifest file 'mpi4jax.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'tests'
warning: no files found matching 'examples'
writing manifest file 'mpi4jax.egg-info/SOURCES.txt'
running check
creating mpi4jax-0.2.15+1.g1074e0c
creating mpi4jax-0.2.15+1.g1074e0c/mpi4jax
creating mpi4jax-0.2.15+1.g1074e0c/mpi4jax.egg-info
creating mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src
creating mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
creating mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/xla_bridge
copying files to mpi4jax-0.2.15+1.g1074e0c...
copying LICENSE.md -> mpi4jax-0.2.15+1.g1074e0c
copying MANIFEST.in -> mpi4jax-0.2.15+1.g1074e0c
copying README.rst -> mpi4jax-0.2.15+1.g1074e0c
copying pyproject.toml -> mpi4jax-0.2.15+1.g1074e0c
copying setup.cfg -> mpi4jax-0.2.15+1.g1074e0c
copying setup.py -> mpi4jax-0.2.15+1.g1074e0c
copying versioneer.py -> mpi4jax-0.2.15+1.g1074e0c
copying mpi4jax/__init__.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax
copying mpi4jax/_deprecations.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax
copying mpi4jax/_version.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax
copying mpi4jax.egg-info/PKG-INFO -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax.egg-info
copying mpi4jax.egg-info/SOURCES.txt -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax.egg-info
copying mpi4jax.egg-info/dependency_links.txt -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax.egg-info
copying mpi4jax.egg-info/requires.txt -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax.egg-info
copying mpi4jax.egg-info/top_level.txt -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax.egg-info
copying mpi4jax/_src/__init__.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src
copying mpi4jax/_src/comm.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src
copying mpi4jax/_src/decorators.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src
copying mpi4jax/_src/flush.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src
copying mpi4jax/_src/utils.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src
copying mpi4jax/_src/validation.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src
copying mpi4jax/_src/collective_ops/__init__.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/allgather.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/allreduce.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/alltoall.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/bcast.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/gather.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/recv.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/reduce.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/scan.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/scatter.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/send.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/sendrecv.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/xla_bridge/__init__.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/xla_bridge
copying mpi4jax/_src/xla_bridge/cuda_runtime_api.pxd -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/xla_bridge
copying mpi4jax/_src/xla_bridge/mpi_xla_bridge.pxd -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/xla_bridge
copying mpi4jax/_src/xla_bridge/mpi_xla_bridge.pyx -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/xla_bridge
copying mpi4jax/_src/xla_bridge/mpi_xla_bridge_cpu.pyx -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/xla_bridge
copying mpi4jax/_src/xla_bridge/mpi_xla_bridge_gpu.pyx -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/xla_bridge
Writing mpi4jax-0.2.15+1.g1074e0c/setup.cfg
UPDATING mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_version.py
set mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_version.py to '0.2.15+1.g1074e0c'
creating dist
Creating tar archive
removing 'mpi4jax-0.2.15+1.g1074e0c' (and everything under it)
```

Note how the tests are missing.

```bash
$ pip install setuptools-scm
Collecting setuptools-scm
  Using cached setuptools_scm-6.0.0-py3-none-any.whl (27 kB)
Requirement already satisfied: setuptools>=45 in /Users/dion/.virtualenvs/tempenv-7e7384267fb0/lib/python3.9/site-packages (from setuptools-scm) (51.3.3)
Installing collected packages: setuptools-scm
Successfully installed setuptools-scm-6.0.0

$ git clean -fxd
$ python setup.py sdist
**************************************************
*** WARNING: CUDA path not found
*** WARNING: (GPU extensions will not be built)
**************************************************
Compiling mpi4jax/_src/xla_bridge/mpi_xla_bridge.pyx because it changed.
Compiling mpi4jax/_src/xla_bridge/mpi_xla_bridge_cpu.pyx because it changed.
[1/2] Cythonizing mpi4jax/_src/xla_bridge/mpi_xla_bridge.pyx
[2/2] Cythonizing mpi4jax/_src/xla_bridge/mpi_xla_bridge_cpu.pyx
running sdist
running egg_info
creating mpi4jax.egg-info
writing mpi4jax.egg-info/PKG-INFO
writing dependency_links to mpi4jax.egg-info/dependency_links.txt
writing requirements to mpi4jax.egg-info/requires.txt
writing top-level names to mpi4jax.egg-info/top_level.txt
writing manifest file 'mpi4jax.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'tests'
warning: no files found matching 'examples'
writing manifest file 'mpi4jax.egg-info/SOURCES.txt'
running check
creating mpi4jax-0.2.15+1.g1074e0c
creating mpi4jax-0.2.15+1.g1074e0c/.github
creating mpi4jax-0.2.15+1.g1074e0c/.github/workflows
creating mpi4jax-0.2.15+1.g1074e0c/conf
creating mpi4jax-0.2.15+1.g1074e0c/docs
creating mpi4jax-0.2.15+1.g1074e0c/docs/_static
creating mpi4jax-0.2.15+1.g1074e0c/examples
creating mpi4jax-0.2.15+1.g1074e0c/mpi4jax
creating mpi4jax-0.2.15+1.g1074e0c/mpi4jax.egg-info
creating mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src
creating mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
creating mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/xla_bridge
creating mpi4jax-0.2.15+1.g1074e0c/tests
creating mpi4jax-0.2.15+1.g1074e0c/tests/collective_ops
copying files to mpi4jax-0.2.15+1.g1074e0c...
copying .flake8 -> mpi4jax-0.2.15+1.g1074e0c
copying .gitattributes -> mpi4jax-0.2.15+1.g1074e0c
copying .gitignore -> mpi4jax-0.2.15+1.g1074e0c
copying .pre-commit-config.yaml -> mpi4jax-0.2.15+1.g1074e0c
copying .readthedocs.yml -> mpi4jax-0.2.15+1.g1074e0c
copying LICENSE.md -> mpi4jax-0.2.15+1.g1074e0c
copying MANIFEST.in -> mpi4jax-0.2.15+1.g1074e0c
copying README.rst -> mpi4jax-0.2.15+1.g1074e0c
copying pyproject.toml -> mpi4jax-0.2.15+1.g1074e0c
copying setup.cfg -> mpi4jax-0.2.15+1.g1074e0c
copying setup.py -> mpi4jax-0.2.15+1.g1074e0c
copying versioneer.py -> mpi4jax-0.2.15+1.g1074e0c
copying .github/workflows/build-docs.yml -> mpi4jax-0.2.15+1.g1074e0c/.github/workflows
copying .github/workflows/covecov-coverage.yml -> mpi4jax-0.2.15+1.g1074e0c/.github/workflows
copying .github/workflows/mpi_tests.yml -> mpi4jax-0.2.15+1.g1074e0c/.github/workflows
copying .github/workflows/pre-commit.yml -> mpi4jax-0.2.15+1.g1074e0c/.github/workflows
copying .github/workflows/python-publish.yml -> mpi4jax-0.2.15+1.g1074e0c/.github/workflows
copying conf/ompi_rootenv.patch -> mpi4jax-0.2.15+1.g1074e0c/conf
copying conf/travis-install-mpi.sh -> mpi4jax-0.2.15+1.g1074e0c/conf
copying docs/Makefile -> mpi4jax-0.2.15+1.g1074e0c/docs
copying docs/api.rst -> mpi4jax-0.2.15+1.g1074e0c/docs
copying docs/conf.py -> mpi4jax-0.2.15+1.g1074e0c/docs
copying docs/environment.yml -> mpi4jax-0.2.15+1.g1074e0c/docs
copying docs/index.rst -> mpi4jax-0.2.15+1.g1074e0c/docs
copying docs/installation.rst -> mpi4jax-0.2.15+1.g1074e0c/docs
copying docs/make.bat -> mpi4jax-0.2.15+1.g1074e0c/docs
copying docs/shallow-water-source.rst -> mpi4jax-0.2.15+1.g1074e0c/docs
copying docs/shallow-water.rst -> mpi4jax-0.2.15+1.g1074e0c/docs
copying docs/sharp-bits.rst -> mpi4jax-0.2.15+1.g1074e0c/docs
copying docs/usage.rst -> mpi4jax-0.2.15+1.g1074e0c/docs
copying docs/_static/shallow-water.mp4 -> mpi4jax-0.2.15+1.g1074e0c/docs/_static
copying examples/shallow_water.py -> mpi4jax-0.2.15+1.g1074e0c/examples
copying mpi4jax/__init__.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax
copying mpi4jax/_deprecations.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax
copying mpi4jax/_version.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax
copying mpi4jax.egg-info/PKG-INFO -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax.egg-info
copying mpi4jax.egg-info/SOURCES.txt -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax.egg-info
copying mpi4jax.egg-info/dependency_links.txt -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax.egg-info
copying mpi4jax.egg-info/requires.txt -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax.egg-info
copying mpi4jax.egg-info/top_level.txt -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax.egg-info
copying mpi4jax/_src/__init__.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src
copying mpi4jax/_src/comm.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src
copying mpi4jax/_src/decorators.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src
copying mpi4jax/_src/flush.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src
copying mpi4jax/_src/utils.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src
copying mpi4jax/_src/validation.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src
copying mpi4jax/_src/collective_ops/__init__.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/allgather.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/allreduce.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/alltoall.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/bcast.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/gather.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/recv.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/reduce.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/scan.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/scatter.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/send.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/collective_ops/sendrecv.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/collective_ops
copying mpi4jax/_src/xla_bridge/__init__.py -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/xla_bridge
copying mpi4jax/_src/xla_bridge/cuda_runtime_api.pxd -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/xla_bridge
copying mpi4jax/_src/xla_bridge/mpi_xla_bridge.pxd -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/xla_bridge
copying mpi4jax/_src/xla_bridge/mpi_xla_bridge.pyx -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/xla_bridge
copying mpi4jax/_src/xla_bridge/mpi_xla_bridge_cpu.pyx -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/xla_bridge
copying mpi4jax/_src/xla_bridge/mpi_xla_bridge_gpu.pyx -> mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_src/xla_bridge
copying tests/conftest.py -> mpi4jax-0.2.15+1.g1074e0c/tests
copying tests/test_decorators.py -> mpi4jax-0.2.15+1.g1074e0c/tests
copying tests/test_deprecations.py -> mpi4jax-0.2.15+1.g1074e0c/tests
copying tests/test_examples.py -> mpi4jax-0.2.15+1.g1074e0c/tests
copying tests/test_flush.py -> mpi4jax-0.2.15+1.g1074e0c/tests
copying tests/test_invalid_jaxlib.py -> mpi4jax-0.2.15+1.g1074e0c/tests
copying tests/test_validation.py -> mpi4jax-0.2.15+1.g1074e0c/tests
copying tests/collective_ops/test_allgather.py -> mpi4jax-0.2.15+1.g1074e0c/tests/collective_ops
copying tests/collective_ops/test_allreduce.py -> mpi4jax-0.2.15+1.g1074e0c/tests/collective_ops
copying tests/collective_ops/test_allreduce_matvec.py -> mpi4jax-0.2.15+1.g1074e0c/tests/collective_ops
copying tests/collective_ops/test_alltoall.py -> mpi4jax-0.2.15+1.g1074e0c/tests/collective_ops
copying tests/collective_ops/test_bcast.py -> mpi4jax-0.2.15+1.g1074e0c/tests/collective_ops
copying tests/collective_ops/test_common.py -> mpi4jax-0.2.15+1.g1074e0c/tests/collective_ops
copying tests/collective_ops/test_gather.py -> mpi4jax-0.2.15+1.g1074e0c/tests/collective_ops
copying tests/collective_ops/test_reduce.py -> mpi4jax-0.2.15+1.g1074e0c/tests/collective_ops
copying tests/collective_ops/test_scan.py -> mpi4jax-0.2.15+1.g1074e0c/tests/collective_ops
copying tests/collective_ops/test_scatter.py -> mpi4jax-0.2.15+1.g1074e0c/tests/collective_ops
copying tests/collective_ops/test_send_and_recv.py -> mpi4jax-0.2.15+1.g1074e0c/tests/collective_ops
copying tests/collective_ops/test_sendrecv.py -> mpi4jax-0.2.15+1.g1074e0c/tests/collective_ops
Writing mpi4jax-0.2.15+1.g1074e0c/setup.cfg
UPDATING mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_version.py
set mpi4jax-0.2.15+1.g1074e0c/mpi4jax/_version.py to '0.2.15+1.g1074e0c'
creating dist
Creating tar archive
removing 'mpi4jax-0.2.15+1.g1074e0c' (and everything under it)
```

Tests are there.

Note that this is current master which doesn't use `setuptools-scm`. So just having it installed changes the behavior...

**Comment by PhilipVinc** [comment]
Yeah, I had noticed that.
Because the Github Action did not load the tests folder, while locally I had it.
I really don't understand.

Maybe we should have a test that just package up the sdist and tries to install it locally and inspects the tarball

**Comment by dionhaefner** [comment]
I think `setuptools-scm` does some stuff in the background to ensure that everything that is tracked by git is included in `sdist`, even if you don't use `setuptools-scm` in the project. I'm glad we got rid of it.

We could have that test you propose. I would also suggest we do something in the "publish" GitHub Action after building the tarball. E.g., install `mpi4jax` from the tarball and make sure the tests pass before pushing to PyPI.

**Pull request merged**
