### PR TITLE
Always use Cython implementation

### LINKED ISSUE #9: Use Cython wrappers even in non-JIT code?
Currently we implement every primitive twice, once via `mpi4py` for use in non-jitted code, and once via Cython for jitted code. Instead, we could also replace the non-jit implementations with

```python
def send_impl(*args, **kwargs):
    return xla.apply_primitive(send_p, *args, **kwargs)
```

which would then always apply our Cython implementation.

#### Pro:
- Less code to maintain
- Consistent logging and debugging behavior (with `MPI4JAX_DEBUG`)
- Consistent user experience regarding array types and validation

#### Con:
- Our wrappers are more rudimentary than `mpi4py`s with less validation and limited errors
- No way to use `mpi4jax` without the Cython extensions

### PR DESCRIPTION
**Pull request by dionhaefner**
What do you think of this? I had to introduce a hashable dummy type to work around https://github.com/google/jax/issues/4280, but I kinda like it because it uses the memory address of the underlying MPI object for caching (which should be more invariant than object id).

This removes quite a bit of boilerplate from the primitive implementations.

Fixes #9

### CODE REVIEW

**Comment by PhilipVinc** [comment]
I like the hashable wrapper idea.

I dislike the try-catch statement in `to_mpi_ptr`. Are you sure there is no other way?

I think we should also address #20 before merging this?

**Comment by dionhaefner** [comment]
I can handle #20 but I don't see how it's related to this. Fixing #20 just means some additional checks in the `xla_encode` functions (which I don't touch here).  I can make another PR for the validation.

Why don't you like the `try-except`? The alternative is checking the type of the MPI object, and using `addressof` if it's `MPI.Status` and otherwise `handleof`. I like the duck approach a bit better but if you prefer I can change it to type checking (no strong opinion on that).

**Comment by PhilipVinc** [comment]
I'd expect a try-catch block to be much more expensive than checking if an object has the method `handleof` or not.
Then the code will be compiled in XLA so... who cares.

I'm not a python expert at all (Julia being my main language lately), so I trust your judgement in what is more efficient.
Your call!

**Comment by dionhaefner** [comment]
No need to worry about performance here, this is in the microsecond range :) 
(and is only executed during tracing)

`try-except` is more robust to upstream changes in `mpi4py`, so I'd rather keep that.

I'll resolve the conflicts and merge if there's nothing else?

**Comment by PhilipVinc** [comment]
yes

**Pull request merged**
