### PR TITLE
cleanup main module

### PR DESCRIPTION
**Pull request by PhilipVinc**
I add a small utility, `_hide_submodules` that hides modules generated by files by prepending an underscore. 
I prefer it to del because it leaves them available.

With this, tab completion gives the following:
```python
>>> import mpi4jax
>>> mpi4jax.#\tab \tab
mpi4jax.Allreduce(                   mpi4jax.Bcast(                       mpi4jax.disable_omnistaging_warning( mpi4jax.Recv(                        mpi4jax.Send(                        mpi4jax.Sendrecv(
```
and
```python
>>> import mpi4jax
>>> mpi4jax._#\tab \tab
mpi4jax._collective_ops mpi4jax._flush(         mpi4jax._utils          mpi4jax._validation     mpi4jax._version        mpi4jax._warn
```

### CODE REVIEW

**Comment by dionhaefner** [comment]
Can't we just rename them to `_something` instead of `something`?

**Comment by PhilipVinc** [comment]
that's what it does

**Comment by dionhaefner** [comment]
I mean `$ git mv collective_ops _collective_ops` :)

**Comment by PhilipVinc** [comment]
ah.
Yes, indeed it's possible.
I don't like having underscored files though.
We would also have to move all files in mpi4jax/
And remember to prepend an underscore always

**Comment by dionhaefner** [comment]
We could also adopt this structure as in most Deepmind projects:

https://github.com/deepmind/rlax/tree/master/rlax

I.e., have everything in `_src` and then use non-underscored names.

**Comment by PhilipVinc** [comment]
I think mpi4jax is relatively a simple project that we don't need such a more complicated structure?
I simply wanted a way to keep the main module clean of anything that is not part of the public API.
And a way to ensure automatically that things that end up being part of the public API do so because we explicitly choose to do so.

**Comment by dionhaefner** [comment]
I understand the goal but I am really not a fan of something like

```python
>>> import mpi4jax.collective_ops
>>> mpi4jax.collective_ops
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'mpi4jax' has no attribute 'collective_ops'
```

It's just surprising behavior, and I fear this could trip some editors and 3rd-party tools up.

So I think the only clean way to achieve this is to rename our models and stick to it. I have no preference for any particular naming scheme, so you can decide what you prefer. The suggestions above boil down to:

```
mpi4jax/
- __init__.py
- _collective_ops/
-- ...
- _utils.py
- ...
```

or

```
mpi4jax/
-  __init__.py
- _src/
-- collective_ops/
--- ...
-- utils.py
```

**Comment by PhilipVinc** [comment]
Ok, that's a good point.

**Comment by PhilipVinc** [comment]
Ok, I went for the `_src` path.
While I was at it, I also renamed functions to underscore and added deprecation warnings.

I only need to update the tests

**Comment by PhilipVinc** [comment]
@dionhaefner I'll tag a new release (0.2.11) so I can start using the lowercase names in netket...

**Pull request merged**
