### PR TITLE
include folders needed for running tests

### PR DESCRIPTION
**Pull request by PhilipVinc**
needed for testing the conda recipe

### CODE REVIEW

**Comment by PhilipVinc** [comment]
@dionhaefner 
I think that now we depend on `setuptools` at runtime:
from the conda recipe testing, which is very picky about installed packages...

```python
import: 'mpi4jax'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/mpi4jax_1615988896238/test_tmp/run_test.py", line 2, in <module>
    import mpi4jax
  File "/home/conda/feedstock_root/build_artifacts/mpi4jax_1615988896238/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/site-packages/mpi4jax/__init__.py", line 9, in <module>
    from ._src import (  # noqa: E402
  File "/home/conda/feedstock_root/build_artifacts/mpi4jax_1615988896238/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/site-packages/mpi4jax/_src/__init__.py", line 22, in <module>
    from pkg_resources import Requirement
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by dionhaefner** [comment]
Yes, we do. What do you think, add a dependency or add a poor man's parser?

```python
JAXLIB_MIN_VERSION = (...)
if jaxlib.__version__.split('.') < JAXLIB_MIN_VERSION:
   raise ...
```

**Comment by PhilipVinc** [comment]
I'd try to avoid such a bulky dependency

**Comment by PhilipVinc** [comment]
can't we just parse the first three version numbers (if they are there?) and discard any additional letters/stuff

**Comment by dionhaefner** [comment]
That's what the poor man's parser does.

**Pull request merged**
