### PR TITLE
Add sphinx documentation

### PR DESCRIPTION
**Pull request by dionhaefner**

### CODE REVIEW

**Comment by dionhaefner** [comment]
Done with the first round of doc writing. @PhilipVinc would love to hear what you think. To build the docs you can do

```bash
$ git checkout docs
$ pip install sphinx sphinx-rtd-theme
$ cd docs
$ make html
```

**Comment by PhilipVinc** [comment]
I've added some details on the MPI library selection, and I've warned against using the coda version in HPC environments because you can't customise the MPI library.

tell me if that is good for you.

--

About the rest, it seems mainly good to me. 
I'm just wondering if we could add some type annotations according to PEPXXX instead of documenting types in the docstrings? This is also what jax is doing, and having (eventually) support for mypy would be nice. What do you think?

**Comment by dionhaefner** [comment]
I'm indifferent to type annotations. I've used them heavily in one project and didn't think that they added any value in terms of catching bugs via `mypy`.

If this is just for the sake of cleaner docstrings, then why not. But we should merge this first regardless.

I'll add a paragraph on `jax.grad` and then merge if that's OK with you.

**Comment by dionhaefner** [comment]
Somewhat of an empty promise, isn't it? :)

Since we can only differentiate through `Allreduce(op=MPI.SUM)`. I'll add it, but I wouldn't make it a major selling point.

**Comment by PhilipVinc** [comment]
Ok, let's leave the type annotations for the future then.

If you mention the grad, then squash and merge ahead.

**Comment by PhilipVinc** [comment]
> Somewhat of an empty promise, isn't it? :)

yeah, fair enough. Though I'd like to eventually address that.
Let's say 'differentiate through some of those primitives' then

**Pull request merged**
